kind: Deployment
apiVersion: apps/v1
metadata:
   name: tomcat-app
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: tomcat-app
   template:
      metadata:
        labels:
          app: tomcat-app
      spec:
       containers:
        - name: tomcat-app
          image: mursalindocker111/ansible-jenkins
          imagePullPolicy: Always
          ports:
          - containerPort: 80