kind: Service                             
apiVersion: v1
metadata:
  name: tomcat-app
  labels:
    app: tomcat-app
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: tomcat-app                   
  type: LoadBalancer                   
